version: '3'
services:
  mt2021-back:
    build: .
    restart: always
    container_name: mt2021-back
    networks:
      - mt2021-network
    ports:
      - 8080:8080
    environment:
      POSTGRES_URL: mt2021-backdb:5432
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgres
  mt2021-backdb:
    image: postgres:12.4
    restart: always
    container_name: mt2021-backdb
    networks:
      - mt2021-network
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - ./postgres/back:/var/lib/postgresql/data

networks:
  mt2021-network:
    driver: bridge
